export const productsData = [
  {
    id: 1,
    name: "Travel Maocle",
    price: 600,
    quantity: 1,
    inStock: 20,
    category: "tops",
    imageUrl: "./images/Travel Maocle.png",
    forWedding: false,
  },
  {
    id: 2,
    name: "Terracotta Overshirt",
    price: 400,
    quantity: 1,
    inStock: 20,
    category: "tops",
    imageUrl: "./images/Terracotta Overshirt.png",
    forWedding: false,
  },
  {
    id: 3,
    name: "Rosie Red Overshirt",
    price: 350,
    quantity: 1,
    inStock: 20,
    category: "tops",
    imageUrl: "./images/Rosie Red Overshirt.png",
    forWedding: false,
  },
  {
    id: 4,
    name: "Checked Formalshirt",
    price: 500,
    quantity: 1,
    inStock: 20,
    category: "tops",
    imageUrl: "./images/Checked Formalshirt.png",
    forWedding: false,
  },
  {
    id: 5,
    name: "Green Suit Jacket",
    price: 240,
    quantity: 1,
    inStock: 20,
    category: "suits",
    imageUrl: "./images/Green Suit Jacket.png",
    forWedding: true,
  },
  {
    id: 6,
    name: "Green Trousers",
    price: 330,
    quantity: 1,
    inStock: 20,
    category: "bottoms",
    imageUrl: "./images/Green Trousers.png",
    forWedding: true,
  },
  {
    id: 7,
    name: "Red Suit Vest",
    price: 220,
    quantity: 10,
    inStock: 20,
    category: "suits",
    imageUrl: "./images/Red Suit Vest.png",
    forWedding: true,
  },
  {
    id: 8,
    name: "Beige Trousers",
    price: 700,
    quantity: 1,
    inStock: 20,
    category: "bottoms",
    imageUrl: "./images/Beige Trousers.png",
    forWedding: true,
  },
  {
    id: 9,
    name: "Checked Blazer",
    price: 800,
    quantity: 1,
    inStock: 20,
    category: "suits",
    imageUrl: "./images/Checked Blazer.png",
    forWedding: true,
  },
  {
    id: 10,
    name: "Checked Trousers",
    price: 430,
    quantity: 1,
    inStock: 20,
    category: "bottoms",
    imageUrl: "./images/Checked Trousers.png",
    forWedding: true,
  },
  {
    id: 11,
    name: "Pink Blazer",
    price: 660,
    quantity: 1,
    inStock: 20,
    category: "suits",
    imageUrl: "./images/Pink Blazer.png",
    forWedding: true,
  },
  {
    id: 12,
    name: "Blue Checked Blazer",
    price: 880,
    quantity: 1,
    inStock: 20,
    category: "suits",
    imageUrl: "./images/Blue Checked Blazer.png",
    forWedding: true,
  },
];
